### ISSUE TITLE
Core Exception using sf_banners 4.0.3

### ISSUE THREAD

**Issue by frikas** [derhansen/sf_banners#213]
Dear all,

I am using Typo3 V8.7.32 and have installed the extension sf_banners V4.0.3.

Unfortunately I am receiving very frequently Typo3 core exceptions due to the installed "sf_banners" extension. What did I miss in the configuration of the "sf_banners" extension?

See attached a file with two samples of the Typo3 core excepion!

Please help to solve the problem!

[typo3-v8-7-32_sf_banners_core-exception.txt](https://github.com/derhansen/sf_banners/files/4633144/typo3-v8-7-32_sf_banners_core-exception.txt)

Best regards
Fritz

**Comment by derhansen** [comment]
Those log entries are created from automated hacking attempts that are logged to TYPO3 sys_log due to a misconfiguration in your TYPO3 website.

Please make sure, that you set `[FE][pageNotFoundOnCHashError] = true` in TYPO3 install tool as shown below.

![image](https://user-images.githubusercontent.com/2629896/82032190-2b5f8900-969b-11ea-9802-f992c5d38cdc.png)

This should resolve your problem. I'm closing the issue, as it is not related to sf_banners
