### ISSUE TITLE
google indexing banners

### ISSUE THREAD

**Issue by piotrburda** [derhansen/sf_banners#215]
TYPO3 7.6.32 and sf_banners 3.0.1
I realized that on my site, when i make site search google is indexing banners, example: site:www.sitename.pl tx_sfbanners_pi1, i have more than 1000 results look like: [https://www.google.com/url?sa=t&rct=j&q=&esrc=s&source=web&cd=&cad=rja&uact=8&ved=2ahUKEwj36b3TrIvsAhXxk4sKHRGjDmY45gEQFjAAegQIBxAB&url=https%3A%2F%2Fwww.narty.pl%2Fski-atlas%2Faustria%2Faustria-karnety-na-wiele-osrodkow%2Fsilvretta%2F%3FL%3D0%26type%3D10386%26tx_sfbanners_pi1%255Baction%255D%3DgetBanners%26tx_sfbanners_pi1%255Bcontroller%255D%3DBanner%26tx_sfbanners_pi1%255BcurrentPageUid%255D%3D10432%26tx_sfbanners_pi1%255Bhmac%255D%3D0e53ba807fe9a4d4f45db3257080adf508fff4e9%26tx_sfbanners_pi1%255BstartingPoint%255D%3D10386%26tx_sfbanners_pi1%255Bcategories%255D%3D2%26tx_sfbanners_pi1%255BdisplayMode%255D%3Drandom%26cHash%3De8a327933f9ebeeed56d8d053aac8e97&usg=AOvVaw093M4pOdhrBKoGIL5fSXW3](https://www.google.com/url?sa=t&rct=j&q=&esrc=s&source=web&cd=&cad=rja&uact=8&ved=2ahUKEwj36b3TrIvsAhXxk4sKHRGjDmY45gEQFjAAegQIBxAB&url=https%3A%2F%2Fwww.narty.pl%2Fski-atlas%2Faustria%2Faustria-karnety-na-wiele-osrodkow%2Fsilvretta%2F%3FL%3D0%26type%3D10386%26tx_sfbanners_pi1%255Baction%255D%3DgetBanners%26tx_sfbanners_pi1%255Bcontroller%255D%3DBanner%26tx_sfbanners_pi1%255BcurrentPageUid%255D%3D10432%26tx_sfbanners_pi1%255Bhmac%255D%3D0e53ba807fe9a4d4f45db3257080adf508fff4e9%26tx_sfbanners_pi1%255BstartingPoint%255D%3D10386%26tx_sfbanners_pi1%255Bcategories%255D%3D2%26tx_sfbanners_pi1%255BdisplayMode%255D%3Drandom%26cHash%3De8a327933f9ebeeed56d8d053aac8e97&usg=AOvVaw093M4pOdhrBKoGIL5fSXW3)
When click it is going to display banner

**Comment by derhansen** [comment]
It seems that some search engines also do index local links they find in the page content.

I therefore added an additional HTTP header in 316e4b3, so search engines are instructed to not index the result of the `getBanners` action.

Since you`re using an old/unsupported version of the extension, the patch will not make it into version 3.x. You could either backport the patch to your local running version of the extension or consider to update to a supported version of TYPO3 / the extension.

Additionally you could add `Disallow: /*tx_sfbanners_pi1    # no banners` to your `robots.txt` file.

**Comment by piotrburda** [comment]
Thanks for quick response, upgrade will follow  TYPO3 upgrade, now will try with robots.txt

**Comment by derhansen** [comment]
News version 5.0.1 has been released. Closing the issue
