### ISSUE TITLE
[BUG] HTML banner output

### ISSUE THREAD

**Issue by bocianl** [derhansen/sf_banners#264]
Hello,
I have a problem with an html banner output.
Banner in HTML format as shown as text instead of HTML code.

<img width="350" alt="image" src="https://github.com/derhansen/sf_banners/assets/3082489/03b82837-d44e-4036-beb2-94c61b74757f">

TYPO3 12.4.13
sf_banners 7.0.3

Thank you.

**Comment by derhansen** [comment]
Thanks for your report. It seems no one really uses this finctionality, since it most likely is broken since the introduction of TYPO3 HTML Sanitizer.

I will publish a fix soon. Change `f:format.html` to `f:format.raw` in https://github.com/derhansen/sf_banners/blob/main/Resources/Private/Partials/Banner/HtmlBanner.html#L3

**Comment by bocianl** [comment]
It works! Thank you! :)

**Comment by derhansen** [comment]
Fixed with 6.1.0 and 7.1.0 - but HTML banners are not disabled by default for non-admin users and must be enabled in extension settings.
